# Generated by Django 4.2.13 on 2024-06-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_receiver', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
