# Generated by Django 5.0.2 on 2024-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_pass',
            field=models.BooleanField(default=True),
        ),
    ]
