# Generated by Django 5.0.2 on 2024-12-08 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_user_add_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorex',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorex', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorex',
            name='winrate',
            field=models.IntegerField(default=0),
        ),
    ]
