# Generated by Django 4.2.12 on 2024-05-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friend_friend_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_userid',
            new_name='friend_id',
        ),
    ]
