# Generated by Django 4.2.13 on 2024-05-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_rename_friend_userid_friend_friend_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=8, null=True)),
                ('request_type', models.CharField(max_length=6, null=True)),
                ('recipient', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
