# Generated by Django 5.0.2 on 2024-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_remove_friendrequest_user_friendship_delete_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('AC', 'accepted'), ('PG', 'pending'), ('DC', 'declined')], default='pending', max_length=10),
        ),
    ]
