# Generated by Django 4.2.13 on 2024-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('AC', 'accepted'), ('PG', 'pending'), ('DC', 'declined')], default='PG', max_length=2),
        ),
    ]
