# Generated by Django 5.0.2 on 2024-11-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_alter_friendship_status'),
        ('notifications', '0011_notification_accept_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
