# Generated by Django 5.0.2 on 2024-11-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_friendship_notification_alter_friendship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='notification',
        ),
    ]
