# Generated by Django 4.2.11 on 2024-04-23 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_remove_game_player1_remove_game_player2_game_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='player1',
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
