# Generated by Django 5.0.2 on 2024-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_players_game_player1_game_player2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_id', models.IntegerField(null=True)),
                ('target_id', models.IntegerField(null=True)),
            ],
        ),
    ]
