# Generated by Django 5.0.2 on 2024-07-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gamerequest_inviter_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameRequest',
        ),
    ]
