# Generated by Django 4.2.16 on 2024-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_game_created_at_remove_game_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='pong', max_length=6),
        ),
    ]
