# Generated by Django 5.0.2 on 2024-11-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_alter_blacklist_banned_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='banned_user_id',
            new_name='blocked_id',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='banned_user',
            new_name='blocked_username',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='banned_time',
            new_name='timestamp',
        ),
    ]
