# Generated by Django 5.0.2 on 2024-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0004_rename_banned_user_id_blacklist_blocked_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blocked_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='blocked_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
