# Generated by Django 4.2.13 on 2024-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
        migrations.AddField(
            model_name='notification',
            name='accept_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='decline_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('UR', 'Unread'), ('RD', 'read')], default='UR', max_length=2),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
