# Generated by Django 4.2.13 on 2024-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_read_remove_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
