# Generated by Django 5.0.2 on 2024-06-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
