# Generated by Django 4.2.13 on 2024-06-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='accept_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='decline_url',
        ),
    ]
