# Generated by Django 4.2.13 on 2024-06-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_accept_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='received',
        ),
    ]
