# Generated by Django 5.0.2 on 2024-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_target_id_notification_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
    ]
