# Generated by Django 4.2.15 on 2024-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friendship_id',
            field=models.IntegerField(null=True),
        ),
    ]
