# Generated by Django 4.2.16 on 2024-11-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_friendship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accept_url',
            field=models.URLField(default=''),
        ),
    ]
