# Generated by Django 5.0.2 on 2024-11-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_remove_friendship_notification'),
        ('notifications', '0011_notification_accept_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
