# Generated by Django 4.2.15 on 2024-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
