# Generated by Django 4.2.16 on 2024-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
