# Generated by Django 4.2.16 on 2024-09-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_bracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='bracket',
        ),
    ]
